"""add claimed at to jobs

Revision ID: 78d9d2cf4f61
Revises: d073f3ec7084
Create Date: 2026-08-25 02:17:46.558080
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '78d9d2cf4f61'
down_revision: Union[str, Sequence[str], None] = 'd073f3ec7084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'claimed_at')
    # ### end Alembic commands ###