import type { Campaign } from '@/types'

export const mockCampaigns: Campaign[] = [
  {
    id: 'camp-001',
    organization_id: 'org-001',
    name: 'Summer Sale Campaign',
    platform: 'google',
    status: 'active',
    objective: 'Conversions',
    spend: 18500,
    clicks: 3200,
    conversions: 111,
    ctr: 2.1,
    cpc: 5.78,
    cpa: 166.6,
    roas: 2.8,
    health_status: 'weak',
  },
  {
    id: 'camp-002',
    organization_id: 'org-001',
    name: 'Brand Awareness',
    platform: 'meta',
    status: 'active',
    objective: 'Reach',
    spend: 12000,
    clicks: 2800,
    conversions: 95,
    ctr: 1.8,
    cpc: 4.29,
    cpa: 126.3,
    roas: 3.2,
    health_status: 'average',
  },
  {
    id: 'camp-003',
    organization_id: 'org-001',
    name: 'Retargeting — Cart Abandoners',
    platform: 'google',
    status: 'active',
    objective: 'Conversions',
    spend: 6500,
    clicks: 1400,
    conversions: 72,
    ctr: 3.5,
    cpc: 4.64,
    cpa: 90.3,
    roas: 4.5,
    health_status: 'strong',
  },
  {
    id: 'camp-004',
    organization_id: 'org-001',
    name: 'New Collection Launch',
    platform: 'meta',
    status: 'paused',
    objective: 'Traffic',
    spend: 4200,
    clicks: 620,
    conversions: 28,
    ctr: 1.2,
    cpc: 6.77,
    cpa: 150.0,
    roas: 2.1,
    health_status: 'average',
  },
  {
    id: 'camp-005',
    organization_id: 'org-001',
    name: 'Holiday Promo 2025',
    platform: 'google',
    status: 'removed',
    objective: 'Conversions',
    spend: 1300,
    clicks: 220,
    conversions: 6,
    ctr: 0.9,
    cpc: 5.91,
    cpa: 216.7,
    roas: 1.4,
    health_status: 'weak',
  },
]
